name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/vocab-be:${{ github.sha }}

      - name: Deploy to K3s via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            # Update deployment image
            kubectl set image deployment/vocab-be \
              vocab-be=${{ secrets.DOCKERHUB_USERNAME }}/vocab-be:${{ github.sha }} \
              -n vocab-be --record

            # Wait for rollout to complete
            kubectl rollout status deployment/vocab-be -n vocab-be --timeout=300s

            # Verify deployment
            echo "Current pods status:"
            kubectl get pods -n vocab-be -l app=vocab-be

            # Clean up old images
            docker image prune -af --filter "until=24h"
